### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by sje30** [sje30/catam-julia#11]
hi @jmb280cam the SIR model looks great.  just one minor suggestion right now, red/green/blue is not a good combination -- 7% of males are r/g colorblind.  can you try another triplet of colors?  If short of ideas, colorbrewer.org is good, e.g. https://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=3

**Comment by jmb280cam** [comment]
Thanks for spotting that, I'll have to keep that in the back of my mind for future case studies. Going by [this colourblindness simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/), the colours :red, :blue, and :gold are one good combination. I've changed the colours to these three in the code files and the Pluto notebook
