### ISSUE TITLE
Mathematical relevance

### ISSUE THREAD

**Issue by jmb280cam** [sje30/catam-julia#12]
I've started working on a Voronoi diagram case study, but I'm not sure how I could turn it from a computationally heavy task into one with a mathematical purpose. Does anyone know of an application / problem that can be solved which I could incorporate?

**Comment by sje30** [comment]
> I've started working on a Voronoi diagram case study, but I'm not sure
> how I could turn it from a computationally heavy task into one with a
> mathematical purpose. Does anyone know of an application / problem
> that can be solved which I could incorporate?

A basic quesion could be something like:  for a set of points under CSR
(Complete Spatial Randomness, i.e. x,y locations drawn from uniform
random distribution), what is the distribution of the number of
edges of Voronoi polygons?  (I've got a paper somewhere that shows what
it should look like)?  And then show how that distribution sharpens
around 6 when you analyse hexagonal lattices (with variable noise
levels).

**Comment by jmb280cam** [comment]
Do you have a link to that paper? Or a quote of the distribution at least?

**Comment by sje30** [comment]
https://paperpile.com/app/p/db88d2cf-7aad-0a40-9b63-2bee259ad31d

**Comment by jmb280cam** [comment]
Thanks
