### ISSUE TITLE
Voronoi case study

### ISSUE THREAD

**Issue by sje30** [sje30/catam-julia#16]
hi @jmb280cam 

the section https://sje30.github.io/catam-julia/casestudies/voronoi/voronoidiagrams.html#5619eeaa-d0ae-4752-987a-abc6b9236725 would be easier to understand I think with a figure to help demonstrate how your algortihm works?  Could you sketch one? (either just in a png or using Plots() to draw it.)

**Comment by jmb280cam** [comment]
Ok, I think I could do a few diagrams in Plots

**Comment by jmb280cam** [comment]
I've added a few diagrams, hope they get the idea across better

**Comment by sje30** [comment]
great, thanks!
