### ISSUE TITLE
document functions using the """...""" markdown notation

### ISSUE THREAD

**Issue by sje30** [sje30/catam-julia#6]
How about using the preferred method for documenting functions?

https://docs.julialang.org/en/v1/manual/documentation/

e.g. "..." or """....multieline""" before the function?

https://github.com/sje30/catam-julia/blob/e07df284906dd9a7e6e1fd6b4e3d94a846fe51c9/casestudies/Permutations/Permutations.jl#L41

**Comment by jmb280cam** [comment]
I've put up an alternative .jl file with documentation. In my opinion it's cluttery for this purpose and obscures the code, but if you think it's important to teach documentation, then I'm happy to keep it that way (obviously I'll change the name and overwrite the original if so)
https://github.com/sje30/catam-julia/blob/main/casestudies/Permutations/Permutationswithdocs.jl
