### ISSUE TITLE
document videos / julia express

### ISSUE THREAD

**Issue by sje30** [sje30/catam-julia#7]
@jmb280cam in the section "Learning Julia and its advantages"

with the bullet points to references, could you add the following two points somewhere

1.  The Computational Thinking course at MIT provides an excellent set of videos to introduce julia to those new to programming.   https://computationalthinking.mit.edu/

2.  the Julia Express https://github.com/bkamins/The-Julia-Express/  is a useful reference guide to the core features of Julia.

**Comment by jmb280cam** [comment]
Done
